import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['index.ts'],
  format: ['cjs', 'esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  esbuildOptions(options) {
    options.jsx = 'automatic';
    options.jsxImportSource = 'react';
  },
  external: [
    'react',
    'react-dom',
    '@tanstack/react-table',
    'lucide-react',
    'class-variance-authority',
    'clsx',
    'tailwind-merge',
    // Optional dependencies
    'jotai',
    'jotai/utils',
    '@tanstack/react-query',
    '@dnd-kit/core',
    '@dnd-kit/sortable',
    '@dnd-kit/utilities',
    '@dnd-kit/modifiers',
    'motion/react',
    'sonner',
    'date-fns',
    'next-intl',
    'nuqs',
    'lodash',
    '@floating-ui/react-dom',
    'react-inlinesvg',
    // Radix UI dependencies
    '@radix-ui/react-slot',
    '@radix-ui/react-dialog',
    '@radix-ui/react-dropdown-menu',
    '@radix-ui/react-menubar',
    '@radix-ui/react-navigation-menu',
    '@radix-ui/react-popover',
    '@radix-ui/react-select',
    '@radix-ui/react-separator',
    '@radix-ui/react-slider',
    '@radix-ui/react-switch',
    '@radix-ui/react-tabs',
    '@radix-ui/react-toast',
    '@radix-ui/react-toggle',
    '@radix-ui/react-toggle-group',
    '@radix-ui/react-tooltip',
    '@radix-ui/react-scroll-area',
    '@radix-ui/react-label',
    '@radix-ui/react-checkbox',
    '@radix-ui/react-avatar',
    '@radix-ui/react-context-menu',
    '@radix-ui/react-collapsible',
    '@radix-ui/react-progress',
    // Internal paths that should be external
    '@/config/site-config',
    '@/config/i18n-config',
    '@/lib/server/actions/database/',
    '@/lib/client/hooks/use-on-click-outside',
    '@/blocks/shared/error-block',
    '@/lib',
  ],
  banner: {
    js: '"use client";',
  },
});
