import { it } from "vitest";
import { chartModelSuite } from "../../../tests/chart-model-suite";
import {
  aggregateChartRows,
  buildChartModel,
  canAddChartFilters,
  chartAggregateParams,
  chartAggregateRequest,
  chartAlignedTicks,
  chartBarLabelRoom,
  chartBucketKey,
  chartBucketLabel,
  chartBucketRange,
  chartFillLayout,
  chartFunnelLayout,
  chartFunnelOrientation,
  chartGroupFilters,
  chartLabel,
  chartMetricUnit,
  chartSettingFields,
  chartShares,
  chartStageList,
  chartValueTicks,
  fitChartLabel,
  loadChartData,
  nextChartBucketKey,
  normalizeChartAggregateResult,
  normalizeChartViewConfig,
  resolveChartSettings,
  withChartFilters,
} from "./chart-model";

import {
  modeDefaultsOf,
  normalizeModeConfig,
  resolveDisplayModes,
  withoutDisabledModeRenderers,
} from "./display-modes";
import { matchesContractFilter } from "./table-contracts";

chartModelSuite(
  it,
  {
    aggregateChartRows,
    buildChartModel,
    canAddChartFilters,
    chartAggregateParams,
    chartAggregateRequest,
    chartAlignedTicks,
    chartBarLabelRoom,
    chartBucketKey,
    chartBucketLabel,
    chartBucketRange,
    chartFunnelLayout,
    chartFunnelOrientation,
    chartFillLayout,
    chartGroupFilters,
    chartLabel,
    chartMetricUnit,
    chartSettingFields,
    chartShares,
    chartStageList,
    chartValueTicks,
    fitChartLabel,
    loadChartData,
    nextChartBucketKey,
    normalizeChartAggregateResult,
    normalizeChartViewConfig,
    resolveChartSettings,
    withChartFilters,
  },
  {
    modeDefaultsOf,
    normalizeModeConfig,
    resolveDisplayModes,
    withoutDisabledModeRenderers,
  },
  { matchesContractFilter }
);
