import { it } from "vitest";
import { connectorSyncSuite } from "../../../tests/connector-sync-suite";
import {
  applyConnectorField,
  CONNECTOR_SKIP,
  canResolveConflicts,
  connectorConflictRules,
  connectorConflictRulesView,
  connectorDirections,
  connectorLabels,
  connectorMappingSections,
  connectorRuleHints,
  connectorScheduleSuffix,
  connectorScreenFields,
  connectorSettingsToSend,
  connectorSyncBlocker,
  connectorSyncFields,
  createConnectorFlow,
  describeConflictRules,
  describePendingConflicts,
  describeSyncPreview,
  describeSyncResult,
  formatSyncValue,
  isConnectorImportSource,
  resolveConnectorSettings,
  resolveSyncSettings,
  toPendingConflicts,
  toSyncPreview,
  toSyncRunResult,
  validateConnectorSettings,
} from "./connector-flow";

connectorSyncSuite(it, {
  CONNECTOR_SKIP,
  applyConnectorField,
  canResolveConflicts,
  connectorConflictRules,
  connectorConflictRulesView,
  connectorDirections,
  connectorLabels,
  connectorMappingSections,
  connectorRuleHints,
  connectorScheduleSuffix,
  connectorScreenFields,
  connectorSettingsToSend,
  connectorSyncBlocker,
  connectorSyncFields,
  createConnectorFlow,
  describeConflictRules,
  describePendingConflicts,
  describeSyncPreview,
  describeSyncResult,
  formatSyncValue,
  isConnectorImportSource,
  resolveConnectorSettings,
  resolveSyncSettings,
  toPendingConflicts,
  toSyncPreview,
  toSyncRunResult,
  validateConnectorSettings,
});
