import { it } from "vitest";
import { connectorFlowSuite } from "../../../tests/connector-flow-suite";
import {
  applyConnectorField,
  CONNECTOR_NO_TARGET,
  CONNECTOR_SKIP,
  connectorErrorMessage,
  connectorFieldOptions,
  connectorKeyFields,
  connectorLabels,
  connectorModes,
  connectorScreenFields,
  connectorSettingsToSend,
  createConnectorFlow,
  defaultConnectorMapping,
  describePushDetails,
  describePushResult,
  hasConnector,
  isConnectorTypeCompatible,
  resolveConnectorSettings,
  toConnectorFailure,
  toConnectorMapping,
  validateConnectorSettings,
} from "./connector-flow";

connectorFlowSuite(it, {
  applyConnectorField,
  CONNECTOR_NO_TARGET,
  CONNECTOR_SKIP,
  connectorScreenFields,
  connectorErrorMessage,
  connectorFieldOptions,
  connectorKeyFields,
  connectorLabels,
  connectorModes,
  connectorSettingsToSend,
  createConnectorFlow,
  defaultConnectorMapping,
  describePushDetails,
  describePushResult,
  hasConnector,
  isConnectorTypeCompatible,
  resolveConnectorSettings,
  toConnectorFailure,
  toConnectorMapping,
  validateConnectorSettings,
});
