import { createHash } from "node:crypto";
import { it } from "vitest";
import { dashboardSchemaSuite } from "../../../tests/dashboard-schema-suite";
import {
  addDashboardSection,
  addDashboardWidget,
  applyDashboardSectionLayout,
  canMoveDashboardWidget,
  canonicalDashboardJson,
  canResizeDashboardWidget,
  checkDashboardReferences,
  createDashboard,
  DASHBOARD_FILTER_TYPES,
  DASHBOARD_ISSUE_SEVERITY,
  DASHBOARD_KPI_METRICS,
  DASHBOARD_LIMITS,
  DASHBOARD_OVERFLOWS,
  DASHBOARD_SECTION_TYPES,
  DASHBOARD_SPARKLINE_BUCKETS,
  DASHBOARD_VERSION,
  DASHBOARD_WIDGET_TYPES,
  dashboardFingerprint,
  dashboardJsonSchema,
  dashboardSlug,
  dashboardText,
  moveDashboardWidget,
  moveWidgetToSection,
  normalizeDashboard,
  removeDashboardWidget,
  resizeDashboardWidget,
  sha256Hex,
  validateDashboard,
} from "./dashboard/dashboard-schema";
import { DISPLAY_MODE_IDS } from "./display-modes";
import { TABLE_DENSITY_OPTIONS } from "./table-contracts";
import { VIEW_CONFIG_KEYS, VIEW_FILTER_OPERATORS } from "./view-config";

dashboardSchemaSuite(it, {
  addDashboardSection,
  addDashboardWidget,
  applyDashboardSectionLayout,
  canMoveDashboardWidget,
  canResizeDashboardWidget,
  canonicalDashboardJson,
  checkDashboardReferences,
  createDashboard,
  DASHBOARD_FILTER_TYPES,
  DASHBOARD_ISSUE_SEVERITY,
  DASHBOARD_KPI_METRICS,
  DASHBOARD_LIMITS,
  DASHBOARD_OVERFLOWS,
  DASHBOARD_SECTION_TYPES,
  DASHBOARD_SPARKLINE_BUCKETS,
  DASHBOARD_VERSION,
  DASHBOARD_WIDGET_TYPES,
  dashboardFingerprint,
  dashboardJsonSchema,
  dashboardSlug,
  dashboardText,
  moveDashboardWidget,
  moveWidgetToSection,
  normalizeDashboard,
  removeDashboardWidget,
  resizeDashboardWidget,
  sha256Hex,
  validateDashboard,
  displayModes: DISPLAY_MODE_IDS,
  densities: TABLE_DENSITY_OPTIONS.map((option) => option.value),
  operators: VIEW_FILTER_OPERATORS,
  viewKeys: VIEW_CONFIG_KEYS,
  sha256: (text) => createHash("sha256").update(text).digest("hex"),
});
