import { it } from "vitest";
import { dashboardEditorSuite } from "../../../tests/dashboard-editor-suite";
import {
  canAddDashboardSection,
  canMoveDashboardSection,
  copyDashboardWidgetView,
  dashboardBlockPropsText,
  dashboardIssueTarget,
  dashboardKindReadsSource,
  dashboardSaveErrors,
  dashboardSectionName,
  dashboardSectionTitleInput,
  dashboardSectionWidgetIds,
  dashboardSourceChoices,
  dashboardSourceMatches,
  dashboardViewEdited,
  dashboardViewEditorActions,
  dashboardViewEditorConfig,
  dashboardViewEditStart,
  dashboardViewToApply,
  dashboardWidgetChoices,
  dashboardWidgetMoveTargets,
  moveDashboardSection,
  moveDashboardWidgetToSection,
  parseDashboardBlockProps,
  recordDashboardViewReport,
  removeDashboardSection,
  renameDashboardSection,
  setDashboardWidgetView,
  updateDashboardWidget,
} from "./dashboard/dashboard-editor-model";
import {
  dashboardTextInput,
  dashboardWidgetDraft,
  dashboardWidgetFromDraft,
  editDashboardText,
} from "./dashboard/dashboard-model";
import {
  addDashboardSection,
  addDashboardWidget,
  dashboardAcceptedSections,
  normalizeDashboard,
  validateDashboard,
} from "./dashboard/dashboard-schema";

dashboardEditorSuite(it, {
  addDashboardSection,
  addDashboardWidget,
  canAddDashboardSection,
  canMoveDashboardSection,
  copyDashboardWidgetView,
  dashboardAcceptedSections,
  dashboardBlockPropsText,
  dashboardIssueTarget,
  dashboardKindReadsSource,
  dashboardSaveErrors,
  dashboardSectionName,
  dashboardSectionTitleInput,
  dashboardSectionWidgetIds,
  dashboardSourceChoices,
  dashboardSourceMatches,
  dashboardTextInput,
  dashboardViewEdited,
  dashboardViewEditorActions,
  dashboardViewEditorConfig,
  dashboardViewEditStart,
  dashboardViewToApply,
  dashboardWidgetChoices,
  dashboardWidgetDraft,
  dashboardWidgetFromDraft,
  dashboardWidgetMoveTargets,
  editDashboardText,
  moveDashboardSection,
  moveDashboardWidgetToSection,
  normalizeDashboard,
  parseDashboardBlockProps,
  recordDashboardViewReport,
  removeDashboardSection,
  renameDashboardSection,
  setDashboardWidgetView,
  updateDashboardWidget,
  validateDashboard,
});
