import { it } from "vitest";
import { dashboardModelSuite } from "../../../tests/dashboard-model-suite";
import {
  addDashboardFilter,
  addDashboardWidget,
  applyGridLayout,
  canMoveLayoutItem,
  canResizeLayoutItem,
  createDashboard,
  dashboardColumnsForWidth,
  dashboardFilterRules,
  dashboardFilterTargetsLabel,
  dashboardLabel,
  dashboardTranslate,
  dashboardWidgetTitle,
  findFreeSpot,
  kpiViewConfig,
  loadDashboardViews,
  mergeDashboardFilters,
  moveLayoutItem,
  normalizeDashboard,
  normalizeLayout,
  removeDashboardWidget,
  resizeLayoutItem,
  resolveLayout,
  setDashboardFilterValue,
  stackLayout,
  validateDashboard,
  widgetFilterSignature,
  withDashboardFilters,
} from "./dashboard/dashboard-model";

dashboardModelSuite(it, {
  addDashboardFilter,
  addDashboardWidget,
  applyGridLayout,
  canMoveLayoutItem,
  canResizeLayoutItem,
  createDashboard,
  dashboardColumnsForWidth,
  dashboardFilterRules,
  dashboardFilterTargetsLabel,
  dashboardLabel,
  dashboardTranslate,
  dashboardWidgetTitle,
  findFreeSpot,
  kpiViewConfig,
  loadDashboardViews,
  mergeDashboardFilters,
  moveLayoutItem,
  normalizeDashboard,
  normalizeLayout,
  removeDashboardWidget,
  resizeLayoutItem,
  resolveLayout,
  setDashboardFilterValue,
  stackLayout,
  validateDashboard,
  widgetFilterSignature,
  withDashboardFilters,
});
