import { it } from "vitest";
import { importModelSuite } from "../../../tests/import-model-suite";
import {
  applyImportField,
  canRunImport,
  createImportFlow,
  describeImportResult,
  IMPORT_NO_KEY,
  importColumnsFrom,
  importErrorLines,
  importFailureLines,
  importJsonErrorMessage,
  importLabels,
  importMappingRows,
  importPreview,
  importSettingsFields,
  importSummaryLines,
  isImportEnabled,
} from "./import-flow";
import {
  coerceImportValue,
  decodeCsvFile,
  defaultImportKey,
  defaultImportMapping,
  detectCsvDelimiter,
  detectDateOrder,
  existingLookupFromRows,
  IMPORT_IGNORE,
  importBatches,
  importFields,
  isImportAuthError,
  looksLikeJson,
  parseCsv,
  parseJsonRecords,
  planImport,
  runImport,
  summarizeImport,
} from "./import-model";

importModelSuite(it, {
  applyImportField,
  canRunImport,
  coerceImportValue,
  createImportFlow,
  decodeCsvFile,
  defaultImportKey,
  defaultImportMapping,
  describeImportResult,
  detectCsvDelimiter,
  detectDateOrder,
  existingLookupFromRows,
  IMPORT_IGNORE,
  IMPORT_NO_KEY,
  importBatches,
  importColumnsFrom,
  importErrorLines,
  importFailureLines,
  importJsonErrorMessage,
  importFields,
  importLabels,
  importMappingRows,
  importPreview,
  importSettingsFields,
  importSummaryLines,
  isImportAuthError,
  isImportEnabled,
  looksLikeJson,
  parseCsv,
  parseJsonRecords,
  planImport,
  runImport,
  summarizeImport,
});
