import { QueryClient } from "@tanstack/vue-query";
import { it } from "vitest";
import { tagCatalogSuite } from "../../../tests/tag-catalog-suite";
import {
  aggregateFacetRows,
  facetEntries,
  facetSelection,
  loadFacetCounts,
  resolveFacets,
  toggleFacetValue,
} from "./facets-model";
import {
  applyTagPatch,
  catalogAfterMerge,
  catalogAfterRemove,
  catalogAfterUpdate,
  catalogWithTag,
  countTagLabel,
  createTag,
  filterTags,
  findTagByName,
  formatTagLabel,
  isTagPatch,
  mergeTagValue,
  normalizeTagList,
  planTagBulkUpdate,
  removeTagValue,
  resolveTagColumn,
  resolveTagLabels,
  selectionTagUsage,
  tagCatalogQuery,
  tagCatalogQueryKey,
  tagColumnForField,
  tagColumnsOf,
  tagCreateName,
  tagLabels,
  tagPickerEnter,
  tagUsageCounts,
  tagUsageRequest,
  withTagCatalogOptions,
  withTagSelected,
} from "./tag-catalog";
import {
  isTagColorName,
  TAG_COLOR_NAMES,
  tagAppearance,
  tagColorValue,
  tagSwatchColor,
} from "./tag-colors";

tagCatalogSuite(
  it,
  {
    applyTagPatch,
    catalogAfterMerge,
    catalogAfterRemove,
    catalogAfterUpdate,
    catalogWithTag,
    countTagLabel,
    createTag,
    filterTags,
    findTagByName,
    formatTagLabel,
    isTagPatch,
    mergeTagValue,
    normalizeTagList,
    planTagBulkUpdate,
    removeTagValue,
    resolveTagColumn,
    resolveTagLabels,
    selectionTagUsage,
    tagCatalogQuery,
    tagCatalogQueryKey,
    tagColumnForField,
    tagColumnsOf,
    tagCreateName,
    tagLabels,
    tagPickerEnter,
    tagUsageCounts,
    tagUsageRequest,
    withTagCatalogOptions,
    withTagSelected,
  },
  {
    isTagColorName,
    TAG_COLOR_NAMES,
    tagAppearance,
    tagColorValue,
    tagSwatchColor,
  },
  () => new QueryClient(),
  {
    aggregateFacetRows,
    facetEntries,
    facetSelection,
    loadFacetCounts,
    resolveFacets,
    toggleFacetValue,
  }
);
