import { test } from "bun:test";
import {
  aggregateChartRows,
  buildChartModel,
  canAddChartFilters,
  chartAggregateParams,
  chartAggregateRequest,
  chartAlignedTicks,
  chartBucketKey,
  chartBucketLabel,
  chartBucketRange,
  chartFunnelLayout,
  chartFunnelOrientation,
  chartGroupFilters,
  chartLabel,
  chartMetricUnit,
  chartSettingFields,
  chartShares,
  chartStageList,
  chartValueTicks,
  fitChartLabel,
  loadChartData,
  nextChartBucketKey,
  normalizeChartAggregateResult,
  normalizeChartViewConfig,
  resolveChartSettings,
  withChartFilters,
} from "../src/components/ui/yayaw-table/utils/chart-model";
import {
  modeDefaultsOf,
  normalizeModeConfig,
  resolveDisplayModes,
  withoutDisabledModeRenderers,
} from "../src/components/ui/yayaw-table/utils/display-modes";
import { matchesContractFilter } from "../src/components/ui/yayaw-table/utils/table-contracts";
import { chartModelSuite } from "./chart-model-suite";

chartModelSuite(
  test,
  {
    aggregateChartRows,
    buildChartModel,
    canAddChartFilters,
    chartAggregateParams,
    chartAggregateRequest,
    chartAlignedTicks,
    chartBucketKey,
    chartBucketLabel,
    chartBucketRange,
    chartFunnelLayout,
    chartFunnelOrientation,
    chartGroupFilters,
    chartLabel,
    chartMetricUnit,
    chartSettingFields,
    chartShares,
    chartStageList,
    chartValueTicks,
    fitChartLabel,
    loadChartData,
    nextChartBucketKey,
    normalizeChartAggregateResult,
    normalizeChartViewConfig,
    resolveChartSettings,
    withChartFilters,
  },
  {
    modeDefaultsOf,
    normalizeModeConfig,
    resolveDisplayModes,
    withoutDisabledModeRenderers,
  },
  { matchesContractFilter }
);
