import { test } from "bun:test";
import {
  applyConnectorField,
  CONNECTOR_NO_TARGET,
  CONNECTOR_SKIP,
  connectorErrorMessage,
  connectorFieldOptions,
  connectorKeyFields,
  connectorLabels,
  connectorMappingSections,
  connectorModes,
  connectorScreenFields,
  connectorSettingsToSend,
  createConnectorFlow,
  defaultConnectorMapping,
  describePushDetails,
  describePushResult,
  hasConnector,
  isConnectorTypeCompatible,
  resolveConnectorSettings,
  toConnectorFailure,
  toConnectorMapping,
  validateConnectorSettings,
} from "../src/components/ui/yayaw-table/utils/connector-flow";
import { connectorFlowSuite } from "./connector-flow-suite";

connectorFlowSuite(test, {
  applyConnectorField,
  CONNECTOR_NO_TARGET,
  CONNECTOR_SKIP,
  connectorScreenFields,
  connectorErrorMessage,
  connectorFieldOptions,
  connectorKeyFields,
  connectorLabels,
  connectorMappingSections,
  connectorModes,
  connectorSettingsToSend,
  createConnectorFlow,
  defaultConnectorMapping,
  describePushDetails,
  describePushResult,
  hasConnector,
  isConnectorTypeCompatible,
  resolveConnectorSettings,
  toConnectorFailure,
  toConnectorMapping,
  validateConnectorSettings,
});
