import { test } from "bun:test";
import {
  applyConnectorField,
  CONNECTOR_SKIP,
  connectorConflictRules,
  connectorDirections,
  connectorLabels,
  connectorMappingSections,
  connectorRuleHints,
  connectorScheduleSuffix,
  connectorScreenFields,
  connectorSettingsToSend,
  connectorSyncBlocker,
  connectorSyncFields,
  createConnectorFlow,
  describeSyncPreview,
  describeSyncResult,
  formatSyncValue,
  isConnectorImportSource,
  resolveConnectorSettings,
  resolveSyncSettings,
  toSyncPreview,
  toSyncRunResult,
  validateConnectorSettings,
} from "../src/components/ui/yayaw-table/utils/connector-flow";
import { connectorSyncSuite } from "./connector-sync-suite";

connectorSyncSuite(test, {
  CONNECTOR_SKIP,
  applyConnectorField,
  connectorConflictRules,
  connectorDirections,
  connectorLabels,
  connectorMappingSections,
  connectorRuleHints,
  connectorScheduleSuffix,
  connectorScreenFields,
  connectorSettingsToSend,
  connectorSyncBlocker,
  connectorSyncFields,
  createConnectorFlow,
  describeSyncPreview,
  describeSyncResult,
  formatSyncValue,
  isConnectorImportSource,
  resolveConnectorSettings,
  resolveSyncSettings,
  toSyncPreview,
  toSyncRunResult,
  validateConnectorSettings,
});
