import { test } from "bun:test";
import {
  addDashboardFilter,
  addDashboardWidget,
  applyGridLayout,
  canMoveLayoutItem,
  canResizeLayoutItem,
  createDashboard,
  dashboardColumnsForWidth,
  dashboardFilterRules,
  dashboardFilterTargetsLabel,
  dashboardLabel,
  dashboardTranslate,
  dashboardWidgetTitle,
  findFreeSpot,
  kpiViewConfig,
  loadDashboardViews,
  mergeDashboardFilters,
  moveLayoutItem,
  normalizeDashboard,
  normalizeLayout,
  removeDashboardWidget,
  resizeLayoutItem,
  resolveLayout,
  setDashboardFilterValue,
  stackLayout,
  validateDashboard,
  widgetFilterSignature,
  withDashboardFilters,
} from "../src/components/ui/yayaw-table-dashboard/dashboard-model";
import { dashboardModelSuite } from "./dashboard-model-suite";

dashboardModelSuite(test, {
  addDashboardFilter,
  addDashboardWidget,
  applyGridLayout,
  canMoveLayoutItem,
  canResizeLayoutItem,
  createDashboard,
  dashboardColumnsForWidth,
  dashboardFilterRules,
  dashboardFilterTargetsLabel,
  dashboardLabel,
  dashboardTranslate,
  dashboardWidgetTitle,
  findFreeSpot,
  kpiViewConfig,
  loadDashboardViews,
  mergeDashboardFilters,
  moveLayoutItem,
  normalizeDashboard,
  normalizeLayout,
  removeDashboardWidget,
  resizeLayoutItem,
  resolveLayout,
  setDashboardFilterValue,
  stackLayout,
  validateDashboard,
  widgetFilterSignature,
  withDashboardFilters,
});
