import { test } from "bun:test";
import { createHash } from "node:crypto";
import { DISPLAY_MODE_IDS } from "../src/components/ui/yayaw-table/utils/display-modes";
import { TABLE_DENSITY_OPTIONS } from "../src/components/ui/yayaw-table/utils/table-contracts";
import {
  VIEW_CONFIG_KEYS,
  VIEW_FILTER_OPERATORS,
} from "../src/components/ui/yayaw-table/utils/view-config";
import {
  addDashboardSection,
  addDashboardWidget,
  applyDashboardSectionLayout,
  canMoveDashboardWidget,
  canonicalDashboardJson,
  canResizeDashboardWidget,
  checkDashboardReferences,
  createDashboard,
  DASHBOARD_FILTER_TYPES,
  DASHBOARD_ISSUE_SEVERITY,
  DASHBOARD_KPI_METRICS,
  DASHBOARD_LIMITS,
  DASHBOARD_OVERFLOWS,
  DASHBOARD_SECTION_TYPES,
  DASHBOARD_SPARKLINE_BUCKETS,
  DASHBOARD_VERSION,
  DASHBOARD_WIDGET_TYPES,
  dashboardFingerprint,
  dashboardJsonSchema,
  dashboardSlug,
  dashboardText,
  moveDashboardWidget,
  moveWidgetToSection,
  normalizeDashboard,
  removeDashboardWidget,
  resizeDashboardWidget,
  sha256Hex,
  validateDashboard,
} from "../src/components/ui/yayaw-table-dashboard/dashboard-schema";
import { dashboardSchemaSuite } from "./dashboard-schema-suite";

dashboardSchemaSuite(test, {
  addDashboardSection,
  addDashboardWidget,
  applyDashboardSectionLayout,
  canMoveDashboardWidget,
  canResizeDashboardWidget,
  canonicalDashboardJson,
  checkDashboardReferences,
  createDashboard,
  DASHBOARD_FILTER_TYPES,
  DASHBOARD_ISSUE_SEVERITY,
  DASHBOARD_KPI_METRICS,
  DASHBOARD_LIMITS,
  DASHBOARD_OVERFLOWS,
  DASHBOARD_SECTION_TYPES,
  DASHBOARD_SPARKLINE_BUCKETS,
  DASHBOARD_VERSION,
  DASHBOARD_WIDGET_TYPES,
  dashboardFingerprint,
  dashboardJsonSchema,
  dashboardSlug,
  dashboardText,
  moveDashboardWidget,
  moveWidgetToSection,
  normalizeDashboard,
  removeDashboardWidget,
  resizeDashboardWidget,
  sha256Hex,
  validateDashboard,
  displayModes: DISPLAY_MODE_IDS,
  densities: TABLE_DENSITY_OPTIONS.map((option) => option.value),
  operators: VIEW_FILTER_OPERATORS,
  viewKeys: VIEW_CONFIG_KEYS,
  sha256: (text) => createHash("sha256").update(text).digest("hex"),
});
