import { test } from "bun:test";
import {
  canAddDashboardSection,
  canMoveDashboardSection,
  copyDashboardWidgetView,
  dashboardBlockPropsText,
  dashboardIssueTarget,
  dashboardKindReadsSource,
  dashboardSaveErrors,
  dashboardSectionName,
  dashboardSectionTitleInput,
  dashboardSectionWidgetIds,
  dashboardSourceChoices,
  dashboardSourceMatches,
  dashboardViewEdited,
  dashboardViewEditStart,
  dashboardViewToApply,
  dashboardWidgetChoices,
  dashboardWidgetMoveTargets,
  moveDashboardSection,
  moveDashboardWidgetToSection,
  parseDashboardBlockProps,
  recordDashboardViewReport,
  removeDashboardSection,
  renameDashboardSection,
  setDashboardWidgetView,
} from "../src/components/ui/yayaw-table-dashboard/dashboard-editor-model";
import {
  dashboardTextInput,
  dashboardWidgetDraft,
  dashboardWidgetFromDraft,
  editDashboardText,
} from "../src/components/ui/yayaw-table-dashboard/dashboard-model";
import {
  addDashboardSection,
  addDashboardWidget,
  dashboardAcceptedSections,
  normalizeDashboard,
  validateDashboard,
} from "../src/components/ui/yayaw-table-dashboard/dashboard-schema";
import { dashboardEditorSuite } from "./dashboard-editor-suite";

dashboardEditorSuite(test, {
  addDashboardSection,
  addDashboardWidget,
  canAddDashboardSection,
  canMoveDashboardSection,
  copyDashboardWidgetView,
  dashboardAcceptedSections,
  dashboardBlockPropsText,
  dashboardIssueTarget,
  dashboardKindReadsSource,
  dashboardSaveErrors,
  dashboardSectionName,
  dashboardSectionTitleInput,
  dashboardSectionWidgetIds,
  dashboardSourceChoices,
  dashboardSourceMatches,
  dashboardTextInput,
  dashboardViewEdited,
  dashboardViewEditStart,
  dashboardViewToApply,
  dashboardWidgetChoices,
  dashboardWidgetDraft,
  dashboardWidgetFromDraft,
  dashboardWidgetMoveTargets,
  editDashboardText,
  moveDashboardSection,
  moveDashboardWidgetToSection,
  normalizeDashboard,
  parseDashboardBlockProps,
  recordDashboardViewReport,
  removeDashboardSection,
  renameDashboardSection,
  setDashboardWidgetView,
  validateDashboard,
});
