import { test } from "bun:test";
import {
  canToggleFacet,
  clearFacets,
  countFacetValues,
  FACET_EMPTY_KEY,
  facetAggregateParams,
  facetCountParams,
  facetEntries,
  facetKeyTarget,
  facetLabel,
  facetSelection,
  facetsShownIn,
  loadFacetCounts,
  normalizeFacetsConfig,
  resolveFacets,
  selectedFacetCount,
  toggleFacetValue,
  visibleFacetEntries,
} from "../src/components/ui/yayaw-table/utils/facets-model";
import {
  buildFolderDirectory,
  canCreateFolderUnder,
  createFolderRecord,
  defaultNewFolderParent,
  folderChoiceComplete,
  folderChoiceOf,
  folderChoiceText,
  folderFacetLabel,
  folderLocationText,
  folderPathText,
  folderTableOptions,
  folderTreeOf,
  loadFolderDirectory,
  newFolderName,
  newFolderShownIn,
  searchFolders,
  toggleFolderChoice,
} from "../src/components/ui/yayaw-table/utils/folder-directory";
import {
  facetBlockColumn,
  facetBlockEntries,
  facetBlockProblems,
  facetBlockProps,
  facetBlockSchema,
  loadFacetBlockCounts,
  toggleFacetBlockValue,
} from "../src/components/ui/yayaw-table-dashboard/dashboard-facets";
import {
  checkDashboardFilterValue,
  dashboardSourceFilterRules,
} from "../src/components/ui/yayaw-table-dashboard/dashboard-model";
import { facetsSuite } from "./facets-suite";

facetsSuite(test, {
  facets: {
    FACET_EMPTY_KEY,
    canToggleFacet,
    clearFacets,
    countFacetValues,
    facetAggregateParams,
    facetCountParams,
    facetEntries,
    facetKeyTarget,
    facetLabel,
    facetSelection,
    facetsShownIn,
    loadFacetCounts,
    normalizeFacetsConfig,
    resolveFacets,
    selectedFacetCount,
    toggleFacetValue,
    visibleFacetEntries,
  },
  folders: {
    buildFolderDirectory,
    canCreateFolderUnder,
    createFolderRecord,
    defaultNewFolderParent,
    folderChoiceComplete,
    folderChoiceOf,
    folderChoiceText,
    folderFacetLabel,
    folderLocationText,
    folderPathText,
    folderTableOptions,
    folderTreeOf,
    loadFolderDirectory,
    newFolderName,
    newFolderShownIn,
    searchFolders,
    toggleFolderChoice,
  },
  dashboard: { checkDashboardFilterValue, dashboardSourceFilterRules },
  block: {
    facetBlockColumn,
    facetBlockEntries,
    facetBlockProblems,
    facetBlockProps,
    facetBlockSchema,
    loadFacetBlockCounts,
    toggleFacetBlockValue,
  },
});
