import { test } from "bun:test";
import {
  conditionAt,
  retargetCondition,
  updateConditionAt,
  withOperator,
} from "../src/components/ui/yayaw-table/utils/form-conditions";
import {
  acceptPublicFormResponse,
  addFormSection,
  buildPublicFormSnapshot,
  createFormRule,
  evaluateFormView,
  formDraftValues,
  formOperatorLabel,
  formRuleIssueLabel,
  formRuleIssues,
  formRuleSummary,
  formRulesFor,
  formSettingsRows,
  formStepOptional,
  formSteps,
  formSubmission,
  moveFormQuestion,
  normalizeFormViewConfig,
  publicFormSnapshot,
  removeFormRule,
  removeFormSection,
  resolveFormSettings,
  updateFormQuestion,
  upsertFormRule,
  validateFormValues,
} from "../src/components/ui/yayaw-table/utils/form-view";
import { formViewRulesSuite } from "./form-view-rules-suite";

formViewRulesSuite(
  test,
  {
    acceptPublicFormResponse,
    addFormSection,
    buildPublicFormSnapshot,
    createFormRule,
    evaluateFormView,
    formDraftValues,
    formOperatorLabel,
    formRuleIssueLabel,
    formRuleIssues,
    formRuleSummary,
    formRulesFor,
    formSettingsRows,
    formStepOptional,
    formSteps,
    formSubmission,
    moveFormQuestion,
    normalizeFormViewConfig,
    publicFormSnapshot,
    removeFormRule,
    removeFormSection,
    resolveFormSettings,
    updateFormQuestion,
    upsertFormRule,
    validateFormValues,
  },
  { conditionAt, retargetCondition, updateConditionAt, withOperator }
);
