// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"actions.fr.mdx": () => import("../content/docs/actions.fr.mdx?collection=docs"), "actions.mdx": () => import("../content/docs/actions.mdx?collection=docs"), "bulk-actions.fr.mdx": () => import("../content/docs/bulk-actions.fr.mdx?collection=docs"), "bulk-actions.mdx": () => import("../content/docs/bulk-actions.mdx?collection=docs"), "columns.fr.mdx": () => import("../content/docs/columns.fr.mdx?collection=docs"), "columns.mdx": () => import("../content/docs/columns.mdx?collection=docs"), "configuration.fr.mdx": () => import("../content/docs/configuration.fr.mdx?collection=docs"), "configuration.mdx": () => import("../content/docs/configuration.mdx?collection=docs"), "datatable.fr.mdx": () => import("../content/docs/datatable.fr.mdx?collection=docs"), "datatable.mdx": () => import("../content/docs/datatable.mdx?collection=docs"), "index.fr.mdx": () => import("../content/docs/index.fr.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "installation.fr.mdx": () => import("../content/docs/installation.fr.mdx?collection=docs"), "installation.mdx": () => import("../content/docs/installation.mdx?collection=docs"), "query-integration.fr.mdx": () => import("../content/docs/query-integration.fr.mdx?collection=docs"), "query-integration.mdx": () => import("../content/docs/query-integration.mdx?collection=docs"), "server-actions.fr.mdx": () => import("../content/docs/server-actions.fr.mdx?collection=docs"), "server-actions.mdx": () => import("../content/docs/server-actions.mdx?collection=docs"), "setup.fr.mdx": () => import("../content/docs/setup.fr.mdx?collection=docs"), "setup.mdx": () => import("../content/docs/setup.mdx?collection=docs"), "translations.fr.mdx": () => import("../content/docs/translations.fr.mdx?collection=docs"), "translations.mdx": () => import("../content/docs/translations.mdx?collection=docs"), "troubleshooting.fr.mdx": () => import("../content/docs/troubleshooting.fr.mdx?collection=docs"), "troubleshooting.mdx": () => import("../content/docs/troubleshooting.mdx?collection=docs"), "url-state.fr.mdx": () => import("../content/docs/url-state.fr.mdx?collection=docs"), "url-state.mdx": () => import("../content/docs/url-state.mdx?collection=docs"), }),
};
export default browserCollections;