/** Shared declaration used by the React and Vue data-type walkthroughs. */
export const dataTypeColumns = [
  { id: "text", header: "Text", type: "text" as const },
  { id: "string", header: "String", type: "string" as const },
  { id: "number", header: "Number", type: "number" as const },
  { id: "boolean", header: "Boolean", type: "boolean" as const },
  { id: "date", header: "Date", type: "date" as const },
  { id: "code", header: "Code", type: "code" as const },
  { id: "json", header: "JSON", type: "json" as const },
  { id: "url", header: "URL", type: "url" as const },
  { id: "image", header: "Image", type: "image" as const },
  ...(["select", "multiSelect", "tag"] as const).map((type) => ({
    id: `${type}Value`,
    header: type,
    type,
    options: [
      { label: "Number one", value: 1 },
      { label: "String one", value: "1" },
      { label: "False", value: false },
      { label: "Unavailable", value: "locked", disabled: true },
    ],
  })),
  {
    id: "dynamic",
    header: "Dynamic value",
    type: "dynamicType" as const,
    typeKey: "kind",
  },
  { id: "custom", header: "Custom (read-only)", type: "custom" as const },
  { id: "actions", header: "Actions", type: "actions" as const },
];
export const dataTypeRow = {
  id: "types-1",
  text: "Standard text",
  string: "A string",
  number: -12.5,
  boolean: false,
  date: "2026-09-08",
  code: "const active = false;",
  json: { active: false, labels: [1, "1"] },
  url: "https://example.com",
  image: "",
  selectValue: 1,
  multiSelectValue: [1, "1", false],
  tagValue: "1",
  kind: "number",
  dynamic: 0,
  custom: "Application-defined value",
};
